[package]
name = "ankoku"
version = "0.1.0"
edition = "2021"

[features]
debug-mode = []
gc-debug-super-slow = []
cli = ["owo-colors"]

[dependencies]
once_cell = "1.16.0"
owo-colors = { version = "3.5.0", optional = true }
