[package]
name = "escuro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.7"
once_cell = "1.16.0"
owo-colors = "3.5.0"
