[package]
name = "ankoku"
version = "0.1.0"
edition = "2021"

[features]
debug-mode = []
cli = ["owo-colors"]

[dependencies]
num_enum = "0.5.7"
once_cell = "1.16.0"
owo-colors = { version = "3.5.0", optional = true }
